export const leftmenu = [
  {
    id: 1,
    title: "Dashboard",
    icon: "<SpeedOutlinedIcon",
    admin: "Admin",
    student: "Student",
    teacher: "Teacher",
    parent: "Parent",
  },
  {
    id: 2,
    title: "Student",
    icon: "SpeedOutlinedIcon",
    admin: "Admin",
    student: "Student",
    teacher: "Teacher",
    parent: "Parent",
  },
  {
    id: 3,
    title: "Teacher",
    icon: "SpeedOutlinedIcon",
    admin: "Admin",
    student: "Student",
    teacher: "Teacher",
    parent: "Parent",
  },
  {
    id: 4,
    title: "Parent",
    icon: "SpeedOutlinedIcon",
    admin: "Admin",
    student: "Student",
    teacher: "Teacher",
    parent: "Parent",
  },
  {
    id: 4,
    title: "Parent",
    icon: "SpeedOutlinedIcon",
    admin: "Admin",
    student: "Student",
    teacher: "Teacher",
    parent: "Parent",
  },
  {
    id: 4,
    title: "Parent",
    icon: "SpeedOutlinedIcon",
    admin: "Admin",
    student: "Student",
    teacher: "Teacher",
    parent: "Parent",
  },
  {
    id: 4,
    title: "Parent",
    icon: "SpeedOutlinedIcon",
    admin: "Admin",
    student: "Student",
    teacher: "Teacher",
    parent: "Parent",
  },
];
