export const Studentdata = [
  {
    roll: "0221",
    photo: "ali",
    name: "Nikshad Ali",
    gender: "Male",
    class: 2,
    section: "A",
    parent: "Ahmed Ali",
    add: "Jallozai",
    dob: "25-05-190",
    phone: "03329991120",
    email: "test@gmail.com",
  },
  {
    roll: "0221",
    photo: "ali",
    name: "Nikshad Ali",
    gender: "Male",
    class: 2,
    section: "A",
    parent: "Ahmed Ali",
    add: "Jallozai",
    dob: "25-05-190",
    phone: "03329991120",
    email: "test@gmail.com",
  },
  {
    roll: "0221",
    photo: "ali",
    name: "Nikshad Ali",
    gender: "Male",
    class: 2,
    section: "A",
    parent: "Ahmed Ali",
    add: "Jallozai",
    dob: "25-05-190",
    phone: "03329991120",
    email: "test@gmail.com",
  },
  {
    roll: "0221",
    photo: "ali",
    name: "Nikshad Ali",
    gender: "Male",
    class: 2,
    section: "A",
    parent: "Ahmed Ali",
    add: "Jallozai",
    dob: "25-05-190",
    phone: "03329991120",
    email: "test@gmail.com",
  },
  {
    roll: " 0221",
    photo: "ali",
    name: "Nikshad Ali",
    gender: "Male",
    class: 2,
    section: "A",
    parent: "Ahmed Ali",
    add: "Jallozai",
    dob: "25-05-190",
    phone: "03329991120",
    email: "test@gmail.com",
  },
  {
    roll: "0221",
    photo: "ali",
    name: "Nikshad Ali",
    gender: "Male",
    class: 2,
    section: "A",
    parent: "Ahmed Ali",
    add: "Jallozai",
    dob: "25-05-190",
    phone: "03329991120",
    email: "test@gmail.com",
  },
  {
    roll: "0221",
    photo: "ali",
    name: "Nikshad Ali",
    gender: "Male",
    class: 2,
    section: "A",
    parent: "Ahmed Ali",
    add: "Jallozai",
    dob: "25-05-190",
    phone: "03329991120",
    email: "test@gmail.com",
  },
  {
    roll: "0221",
    photo: "ali",
    name: "Nikshad Ali",
    gender: "Male",
    class: 2,
    section: "A",
    parent: "Ahmed Ali",
    add: "Jallozai",
    dob: "25-05-190",
    phone: "03329991120",
    email: "test@gmail.com",
  },
];
